package org.example.model;

import lombok.*;
import org.bson.types.ObjectId;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

import java.time.LocalDateTime;

/**
 * MongoDB document to log API requests and responses.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "req_res_log")
public class RequestResponseLog {

    /** MongoDB autogenerated ID */
    @Id
    private ObjectId _id;

    /** Captures all request-related metadata */
    private RequestData request_logs;

    /** Captures response body and status */
    private ResponseData response_logs;

    /** Timestamp when the log was created */
    @CreatedDate
    @Field("created_at")
    private LocalDateTime created_at;

    /**
     * Inner static class to store request details.
     */
    @Data
    public static class RequestData {
        /** Full request URL (e.g., /api/v1/user) */
        private String url;

        /** Slug used to identify the triggered workflow/task */
        private String slug;

        /** HTTP method (GET, POST, etc.) */
        private String method;

        /** Headers sent in the request */
        private Object headers;

        /** Query parameters in the request */
        private Object params;

        /** Body payload of the request */
        private Object body;
    }

    /**
     * Inner static class to store response details.
     */
    @Data
    public static class ResponseData {
        /** HTTP status code of the response */
        private int status_code;

        /** Full response object (can be a map, string, etc.) */
        private Object response;
    }
}
